# Generated by Django 4.2 on 2023-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name_of_person", models.CharField(max_length=100)),
                ("Image_of_person", models.ImageField(upload_to="pics")),
                ("Details_of_person", models.TextField()),
            ],
        ),
    ]
